# Generated by Django 5.1.3 on 2024-11-19 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('musculation', 'Musculation')], max_length=50)),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('is_using_machine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.equipment')),
            ],
        ),
    ]
